---
- name: Install web server
  hosts: webserver
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: wget
    rule: http
  become: yes
  tasks:
    - name: Ensure installed package
      ansible.builtin.dnf:
        name: 
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
        state: present
    
    - name: Ensure "{{ web_service }}" is enabled and running
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: started
        enabled: yes

    - name: Ensure "{{ firewall_service }}" is enabled and running
      ansible.builtin.service:
        name: "{{ firewall_service }}"
        state: started
        enabled: yes

    - name: Copy index.html using inline content
      ansible.builtin.copy:
        content: "Example web content\n"
        dest: /var/www/html/index.html

    - name: Permit traffic in default zone for "{{ web_service }}" service
      ansible.posix.firewalld:
        service: "{{ rule }}"
        permanent: true
        state: enabled
        immediate: yes

- name: Test web server
  hosts: localhost
  tasks:
    
    - name: Ensure web server is up and running
      ansible.builtin.uri:
        url: http://vm-22-node2-ansible.example.com
        method: GET
        return_content: true
        status_code: 200
