---
- name: Play setup web server
  hosts: webservers
  tasks:
  - name: Ensure http is installed
    ansible.builtin.yum:
      name: httpd
      state: present
  - name: Ensure index.html file exists
    ansible.builtin.copy:
      src: files/index.html
      dest: /var/www/html/index.html
  - name: Ensure httpd is enabled and service module is enabled
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
