---
- name: Using the file module to ensure SELinux file context
  hosts: servers
  become: true
  tasks:
    - name: SELinux file context is set to defaults
      ansible.builtin.file:
        path: /home/automation/users.txt
        seuser: _default
        serole: _default
        setype: _default
        #setype: samba_share_t
        selevel: _default
