---
- name: Update apache
  hosts: webservers
  serial: 1

  tasks:
    - name: Latest version of apache installed
      ansible.builtin.dnf:
        name: httpd
        state: latest
      notify:
        - Restart apache httpd

  # This activity depends from the previous task Notify - Restart apache
  handlers:
    - name: Restart apache httpd
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: restarted
